apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: main-rules
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: main.rules
    rules:
    - alert: HostHighCPULoad
      expr: 100 - (avg by (instance)(rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 50
      for: 2m
      labels:
        severity: warning
        namespace: monitoring
      annotations:
        description: "CPU load on host is over 50 percent \ Value = {{ $value}} \ Instance = {{ $labels.instance }} \n"
        summary: "cpu load is high {{ $labels.namespace}}"
    - alert: KubernetesPodCrashLooping
      expr: increase(kube_pod_container_status_restarts_total[1m]) > 1
      for: 0m
      labels:
        severity: critical
        namespace: monitoring
      annotations:
        summary: Kubernetes pod crash looping (instance {{ $labels.instance }})
        description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: RedisDown
      expr: redis_up == 0
      for: 0m
      labels:
        severity: critical
        namespace: monitoring

      annotations:
        summary: Redis down (instance {{ $labels.instance }})
        description: "Redis instance is down\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: RedisTooManyMasters
      expr: count(redis_instance_info{role="master"}) > 1
      for: 0m
      labels:
        severity: critical
        namespace: monitoring

      annotations:
        summary: Redis too many masters (instance {{ $labels.instance }})
        description: "Redis cluster has too many nodes marked as master.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
